apiVersion: apps/v1
kind: Deployment
metadata:
  name: validator
  namespace: system
  labels:
    app: validator
spec:
  selector:
    matchLabels:
      app: validator
  replicas: 1
  template:
    metadata:
      labels:
        app: validator
    spec:
      serviceAccountName: validator
      containers:
      - command:
        - /ishield-app/k8s-manifest-sigstore
        image: k8s-manifest-sigstore
        imagePullPolicy: Always
        name: manager
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: USE_REMOTE_HANDLER
          value: "false"
        - name: CONTROLLER_CONFIG_KEY
          value: "config.yaml"
        - name: CONTROLLER_CONFIG_NAME
          value: "admission-controller-config"
        - name: REQUEST_HANDLER_CONFIG_KEY
          value: "config.yaml"
        - name: REQUEST_HANDLER_CONFIG_NAME
          value: "request-handler-config"
        - name: LOG_LEVEL
          value: "info"
        - name: LOG_FORMAT
          value: "json"
        ports:
        - containerPort: 9443
          name: validator-port
          protocol: TCP
        livenessProbe:
          exec:
            command: ["ls"]
        readinessProbe:
          exec:
            command: ["ls"]
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 200m
            memory: 200Mi
        volumeMounts:
          - mountPath: /run/secrets/tls
            name: webhook-tls
      volumes:
        - name: webhook-tls
          secret:
            secretName: validator-tls
      terminationGracePeriodSeconds: 10

